- hosts: "{{ target | default('nowhere') }}"
  gather_facts:  false
  become: yes
  tasks:
    - name: Download code from the GitRepo
      git:
        repo: 'https://{{gituser}}:{{gitpass}}@gitee.com/zz_lf/infinity.git'
        dest: "{{dest}}"
    - name: uncompress
      shell: sh run-remote-local.sh {{env}}
      args:
        chdir: "{{dest}}"